#!/bin/zsh

n=1

while true ; do

  q=`date +%H`
  s=`ls /home/player/music | shuf -n1`

  if [[ "$q" == "10" ||
        "$q" == "11" ||
        "$q" == "12" ||
        "$q" == "13" ||
        "$q" == "14" ||
        "$q" == "15" ||
        "$q" == "16" ||
        "$q" == "17" ||
        "$q" == "18" ||
        "$q" == "19" ||
        "$q" == "20" ]] ; then
    mpg123 -q /home/player/music/$s
    sleep 15
    mpg123 -q /home/player/ads/$n.mp3

    let  "n = n + 1"
    if [ $n -gt 3 ]; then
      let "n = 1"
    fi
    sleep 15
  fi
done

